[app]

# (str) Title of your application
title = Cinqic Calculator

# (str) Package name - combined with package.domain below, the final
# Android application ID is package.domain + "." + package.name, i.e.
# com.cinqic.calculator, matching cinqic_calculator.constants.APP_ID.
package.name = calculator

# (str) Package domain (needed for the Android package ID)
package.domain = com.cinqic

# (str) Source code where the main.py live. This directory is packaged as
# the app's root by python-for-android, which is why android/main.py,
# android/logic.py, android/android_constants.py, and android/screens/
# all use flat (non-"android."-prefixed) imports of each other - see the
# docstring at the top of android/main.py.
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,kv,png,jpg,atlas

# IMPORTANT (see android/README.md): buildozer only packages files that
# live under source.dir above. The shared cinqic_calculator core package
# lives outside this directory at ../src/cinqic_calculator, so the CI build
# step must copy or symlink it into this directory (e.g.
# `cp -r ../src/cinqic_calculator android/cinqic_calculator`) *before*
# invoking buildozer. cinqic_calculator has zero third-party dependencies,
# so nothing beyond the copy itself is required for it to import cleanly
# once bundled this way.

# (str) Application versioning - human-readable version string. This is the
# ANDROID app's own version, tracked independently of the desktop app's
# cinqic_calculator.constants.APP_VERSION (currently 1.0.1 - that constant
# is shared with the desktop UI and must not be reused here).
version = 1.0.0

# (int) Application versionCode - the Play Store / package manager's
# machine-readable, monotonically increasing build counter. This is the
# buildozer.spec key for what Android calls versionCode; if omitted,
# buildozer derives one from `version` above instead, so it is set
# explicitly here to keep it independent and predictable.
android.numeric_version = 1

# (list) Application requirements
# Kept minimal on purpose: cinqic_calculator (bundled per the note above)
# has zero third-party dependencies of its own, so nothing beyond Python
# and Kivy is needed to import and run it.
requirements = python3,kivy

# (str) Legacy (pre-adaptive, API<26) launcher icon: the emblem flattened
# onto the app's dark background plate, generated by scripts/process_logo.py
# from the official Cinqic Calculator logo (calculator + clover emblem).
icon.filename = %(source.dir)s/assets/icon/icon_legacy_xxxhdpi.png

# (str) Adaptive icon (API 26+) layers: foreground is the transparent
# emblem alone, sized to the launcher safe zone so no mask (circle,
# squircle, rounded square) clips the calculator or clover; background is
# a flat plate in the app's dark theme color. Both generated by
# scripts/process_logo.py.
icon.adaptive_foreground.filename = %(source.dir)s/assets/icon/icon_foreground.png
icon.adaptive_background.filename = %(source.dir)s/assets/icon/icon_background.png

# (str) Splash screen shown while the app cold-starts.
presplash.filename = %(source.dir)s/assets/icon/presplash.png
presplash.color = #0A0A0A

# (str) Supported orientation (one of: landscape, sensorLandscape,
# portrait, sensorPortrait, user, all)
orientation = portrait

# (int) 1 = fullscreen, 0 = windowed (with system status/nav bars visible)
fullscreen = 0

# (list) Permissions
# Deliberately empty: the app is fully offline (no internet permission) and
# only ever touches its own Kivy-provided private user_data_dir, which
# requires no storage permission on any supported API level.
android.permissions =

# (int) Target Android API - a current, Play-Store-eligible level.
android.api = 34

# (int) Minimum API level. The product owner's test device (Samsung A14 5G)
# ships Android 13/14, well above any of these; 21 is used instead of a
# higher floor purely for broad device compatibility (Android 5.0+), since
# nothing in this app (Kivy, plus the dependency-free cinqic_calculator
# core) requires a newer minimum API to run correctly.
android.minapi = 21

# (list) The Android archs to build for
android.archs = arm64-v8a, armeabi-v7a

# (str) python-for-android version to use. Buildozer clones p4a itself
# rather than using a pip-installed copy, and defaults to tracking p4a's
# master branch - which pairs whatever buildozer version is installed with
# a bleeding-edge toolchain. Pinned to the release that shipped alongside
# buildozer 1.6.0 (see android/requirements-android.txt); keep the two in
# sync when upgrading either.
p4a.branch = v2026.05.09

[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug)
log_level = 2

# (int) Display warning if buildozer is run as root
warn_on_root = 1
